apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongo-db
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=  # base64 encoded 'admin'
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4xMjM=  # base64 encoded 'admin123'

